apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.hello-k8s.s5t.dev
spec:
  group: hello-k8s.s5t.dev
  scope: Namespaced
  names:
    plural: examples
    singular: example
    kind: Example
    listKind: ExampleList
    shortNames:
    - ex
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              comments:
                type: string
              podName:
                type: string
    additionalPrinterColumns:
    - name: Comments
      type: string
      description: Comments about the example
      jsonPath: .spec.comments
    - name: Pod-Name
      type: string
      description: Name of the assigned pod
      jsonPath: .spec.podName